# Generated by Django 4.2.7 on 2025-04-08 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(30, message='Минимальная длительность бронирования - 30 минут'), django.core.validators.MaxValueValidator(240, message='Максимальная длительность бронирования - 4 часа')], verbose_name='Длительность (минуты)'),
        ),
    ]
